name: 'Commit Watch'
description: 'Lint commit messages using Commit Watch'
inputs:
  github_token:
    description: 'Personal access token to update github status.'
    required: true
  artifact_dir:
    description: 'Directory to store run artifacts.'
    required: false
    default: './artifacts'
runs:
  using: 'node12'
  main: 'src/yarn-bootstrap.js'
branding:
  color: blue
  icon: eye
