on: [pull_request]

env:
  ARTIFACT_DIR: ./artifacts

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Create Artifact Dir
        run: mkdir -p ${{ env.ARTIFACT_DIR }}
      - name: Run Action
        uses: ./
        with:
          artifact_dir: ${{ env.ARTIFACT_DIR }}
          github_token: ${{ secrets.GH_TOKEN }}
        env:
          DEBUG: 1
